- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/VisitResource1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/VisitController1_9Test.java
The required feature was to set _startDatetime_ property for _Visit_ to current date if not provided by the client.
> Restws 488

- omod-1.10/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_10/ProgramEnrollmentResource1_10.java
- omod-1.10/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_10/ProgramResource1_10.java
- omod-1.10/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_10/ProgramResource1_10Test.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ProgramEnrollmentResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ProgramResource1_8.java
- omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/RestTestConstants1_8.java
- omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_8/ProgramController1_8Test.java
- omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_8/ProgramEnrollmentController1_8Test.java
- omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ProgramResource1_8Test.java
https://issues.openmrs.org/browse/RESTWS-510
> REST endpoint for 'Program Enrollment'

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/RelationshipResource1_8.java
https://issues.openmrs.org/browse/RESTWS-511
> RESTWS-511 | Exposing end date of relationship

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/RelationshipResource1_8.java
Reverts openmrs/openmrs-module-webservices.rest#127
> Revert "RESTWS-511 | Exposing end date of relationship"

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/RelationshipResource1_8.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/RelationshipResource1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/RelationshipResource1_9Test.java
Pull request for build broken for RESTWS-511
> RESTWS-511 : fix for broken build

- omod-common/src/main/java/org/openmrs/module/webservices/docs/ResourceDoc.java
- omod-common/src/main/java/org/openmrs/module/webservices/docs/ResourceDocCreator.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/api/RestService.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/api/impl/RestServiceImpl.java
https://issues.openmrs.org/browse/RESTWS-361
> RESTWS-361:Add support for SearchHandler to ResourceDoc

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/UserResource1_8.java
- omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/PersonResource1_8Test.java
- omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/UserResource1_8Test.java
We added the requested functionality to the class UserResource1_8. We also added Unit tests to test the original and the extended behavior.
> RESTWS-490: Add functionality to query by role to user resource

- omod-1.10/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_10/ProgramEnrollmentResource1_10.java
- omod-1.10/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_10/ProgramEnrollmentController1_10Test.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/PatientStateResource1_8.java
Reverts openmrs/openmrs-module-webservices.rest#137
> Revert "RESTWS-520: Ability to remove the last selected program state"

- omod-1.10/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_10/ProgramEnrollmentResource1_10.java
- omod-1.10/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_10/ProgramEnrollmentController1_10Test.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/PatientStateResource1_8.java
18Aug2015: Please review and merge.
> RESTWS-520: Ability to remove the last selected program state

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ObsResource1_8.java
- omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ObsResource1_8Test.java
https://issues.openmrs.org/browse/RESTWS-491
review please
> RESTWS-491 Allow obs resource to accept uuid in place of boolean

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/VisitResource1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/VisitController1_9Test.java
> RESTWS-508 Added get all visits

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/EncounterProviderResource1_9.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/EncounterResource1_9.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/EncounterRoleResource1_9.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/ProviderResource1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/RestTestConstants1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ConceptController1_9Test.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ConceptMapTypeController1_9Test.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/EncounterController1_9Test.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/EncounterRoleController1_9Test.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/LocationAttributeTypeController1_9Test.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ObsController1_9Test.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ProviderAttributeController1_9Test.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ProviderAttributeTypeController1_9Test.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ProviderController1_9Test.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/VisitAttributeController1_9Test.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/VisitAttributeTypeController1_9Test.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/VisitTypeController1_9Test.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/EncounterProviderResource1_9Test.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/EncounterResource1_9Test.java
- omod-1.9/src/test/resources/customTestDataset1_9.xml
@dkayiwa et al I have made changes to fix the test that was failing the build as shown https://ci.openmrs.org/browse/RESTWS-RESTWS-414
> RESTWS-443: Adding EncounterProviderResource and associated tests

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ClobDatatypeStorageController.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/FormResourceController1_9.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/EncounterResource1_9.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/FormResource1_9.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/FormResourceResource1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/RestTestConstants1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ClobDatatypeStorageControllerTest.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/FormResourceController1_9Test.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/FormResource1_9Test.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/FormResourceResource1_9Test.java
- omod-1.9/src/test/resources/formResourceTestDataset1_9.xml
- omod-1.9/src/test/resources/formResourcefile.txt
- omod-common/src/main/resources/webModuleApplicationContext.xml
- omod-common/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/MainResourceControllerTest.java
- omod-common/src/test/resource/webModuleApplicationContext-Test.xml
Along with the FormResource sub-resource, I have added controllers to handle ClobDatatypeStorage upload/download/delete.
> RESTWS-523: Added a FormResource sub-resource to Form resource

- omod-1.10/pom.xml
- omod-1.8/pom.xml
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/api/impl/RestHelperServiceImpl.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/response/GenericRestException.java
- omod-common/src/main/resources/webModuleApplicationContext.xml
- pom.xml
Reverts openmrs/openmrs-module-webservices.rest#162
Failing build at https://ci.openmrs.org/browse/RESTWS-RESTWS-467
> Revert "[RESTWS-533] Replace SessionFactory with DbSessionFactory"

- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/EncounterController1_9Test.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/SimpleObject.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/ConversionUtil.java
https://issues.openmrs.org/browse/RESTWS-483
> RESTWS-483: REST API shouldn't depend on the attribute order in the JSON string which sends from the client side.

- omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_8/EncounterController1_8Test.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/EncounterController1_9Test.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/SimpleObject.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/ConversionUtil.java
https://issues.openmrs.org/browse/RESTWS-483
> REST API shouldn't depend on the attribute order in the JSON string hich sends from the client side.

- omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_8/PatientController1_8Test.java
https://issues.openmrs.org/browse/RESTWS-380
> Added test for searching patients with custom representation

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ConceptDescriptionResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ConceptResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/FieldAnswerResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/FormFieldResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/PersonResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/UserResource1_8.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/ConceptReferenceTermMapResource1_9.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/ConversionUtil.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/BaseDelegatingResource.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/BaseDelegatingSubclassHandler.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/DataDelegatingCrudResource.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/DelegatingSubResource.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/MetadataDelegatingCrudResource.java
Reverts openmrs/openmrs-module-webservices.rest#170
> Revert "RESTWS-536: refactoring of getAuditInfo"

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ConceptDescriptionResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ConceptResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/FieldAnswerResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/FormFieldResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/PersonResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/UserResource1_8.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/ConceptReferenceTermMapResource1_9.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/ConversionUtil.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/BaseDelegatingResource.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/BaseDelegatingSubclassHandler.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/DataDelegatingCrudResource.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/DelegatingSubResource.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/MetadataDelegatingCrudResource.java
https://issues.openmrs.org/browse/RESTWS-536
> RESTWS-536: refactoring of getAuditInfo

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ActiveListTypeResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ConceptClassResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/EncounterTypeResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/OrderTypeResource1_8.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/EncounterRoleResource1_9.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/VisitTypeResource1_9.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/util/ReflectionUtil.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/BaseDelegatingResource.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/MetadataDelegatingCrudResource.java
https://issues.openmrs.org/browse/RESTWS-537
> RESTWS-537: Provide default implementation for getRepresentationDescription in MetadataDelegatingCrudResource

- omod-common/src/main/java/org/openmrs/module/webservices/rest/util/SimpleObjectConverter.java
https://issues.openmrs.org/browse/RESTWS-462
> RESTWS-462 | null check for the object that doesn't have a "links".

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/ConceptStopwordResource1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/ConceptStopwordResource1_9Test.java
Jira ticket:
https://issues.openmrs.org/browse/RESTWS-567
> RESTWS-567 Added ConceptStopWord REST URL's

- omod-1.10/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_10/DrugResource1_10.java
- omod-1.10/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_10/DrugController1_10Test.java
https://issues.openmrs.org/browse/RESTWS-565
> RESTWS-565 Missing strength field in Drug resource

- omod-1.12/pom.xml
- omod-1.12/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_12/OrderSetMemberResource1_12.java
- omod-1.12/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_12/OrderSetResource1_12.java
- omod-1.12/src/test/java/org/openmrs/module/webservices/rest/web/RestTestConstants1_12.java
- omod-1.12/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_12/OrderSetController1_12Test.java
- omod-1.12/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_12/OrderSetMemberController1_12Test.java
- omod-1.12/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_12/OrderSetMemberResource1_12Test.java
- omod-1.12/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_12/OrderSetResource1_12Test.java
- omod-1.12/src/test/resources/customTestDataset1_12.xml
- omod/pom.xml
- pom.xml
Added two resources orderSet,
orderSetMember for saving, updating, deleting, orderSets.
(The orderSetMember save/update is taken care by the save/update of orderSet)
> RESTWS-558 | Create a rest resource/api for org.openmrs.OrderSet

- omod-common/src/main/java/org/openmrs/module/webservices/docs/swagger/SwaggerSpecificationCreator.java
This adds the ability to use the `q` search parameter on any `GET` operation that returns a list of results.
> 🔬 Add search query parameter 

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ConceptResource1_8.java
- omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ConceptResource1_8Test.java
@rkorytkowski, please check this.
> RESTWS-582 enable editing concept names

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ConceptResource1_8.java
- omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ConceptResource1_8Test.java
I have exported setNames logic to more general method setHibernateCollectionProperty, which is now invoked by setNames and setDescriptions.
> RESTWS-583 allow editing Concept descriptions

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs1_9/ConceptReferenceTermSearchHandler1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ConceptReferenceTermController1_9Test.java
This pull request makes ConceptReferenceTerm include source in search process, making search by specified source possible.
> RESTWS-598 Implement searching ConceptReferenceTerm by source

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ConceptResource1_8.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ConceptController1_8Test.java
Reverts openmrs/openmrs-module-webservices.rest#216
> Revert "RESTWS-599 Fix updating concept's mappings"

- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/RequestContext.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/AlreadyPaged.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/BasePageableResult.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/NeedsPaging.java
- omod-common/src/test/java/org/openmrs/module/webservices/rest/web/RequestContextTest.java
- omod-common/src/test/java/org/openmrs/module/webservices/rest/web/resource/impl/AlreadyPagedTest.java
- omod-common/src/test/java/org/openmrs/module/webservices/rest/web/resource/impl/NeedsPagingTest.java
Work in progress for https://issues.openmrs.org/browse/RESTWS-601
> RESTWS-601

- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/api/impl/RestServiceImpl.java
created a private method isOpenmrsVersionInVersions to reduce duplication
in RestServiceImpl.initializeResources()
@wluyima I want to refactor the RestServiceImpl class as part of 
https://issues.openmrs.org/browse/RESTWS-610 and https://issues.openmrs.org/browse/RESTWS-613
hope you are ok with me doing it in little steps. Would like to merge more often, so its clear what is done. This way I'll also see clearer through the logic in RestServiceImpl
thanks a lot :)
> Refactor duplication of RestServiceImpl version check

- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/api/impl/RestServiceImpl.java
no need to loop through rest of versions if a match is found
in the versions array
> Break out of foreach if verion is matched

- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/api/impl/RestServiceImpl.java
- omod-common/src/test/java/org/openmrs/module/webservices/rest/web/api/impl/RestServiceImplTest.java
was missing tests, added them.
reduced unneeded nesting of if/else since return in if leaves method anyway
> Add tests for RestServiceImpl.getRepresentation()

- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/api/SearchQuery.java
- omod-common/src/test/java/org/openmrs/module/webservices/rest/web/resource/api/SearchQueryTest.java
* add javadocs to SearchQuery
* add test class for SearchQuery
* simplify SearchQuery.equals() replace obj==null and obj.getClass() !=
getClass() with instanceof operator
see https://issues.openmrs.org/browse/RESTWS-620
> RESTWS-620 Add SearchQueryTest

- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/api/impl/RestServiceImpl.java
Refactor private method RestServiceImpl.initializeResources()
* create private nested class ResourceMetadata to hold a Resource's
metadata [name/supportedClass and order] spread accross
@Resource/@SubResource
* extract method getResourceMetadata() which returns ResourceMetadata for a
Resource class
* extract method isResourceToBeAdded which determines if Resource class
* should
be added to the resource Maps (which act as cache)
* do not use exceptions as control flow
make this class more readable as part of https://issues.openmrs.org/browse/RESTWS-613
> Refactor RestServiceImpl.initializeResources()

- omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_0/ConceptSourceResource2_0.java
- omod-2.1/pom.xml
- omod-2.1/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_1/ConceptSourceResource2_1.java
- omod-2.1/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/RestTestConstants2_1.java
- omod-2.1/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_1/ConceptSourceController2_1Test.java
- omod-2.1/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_1/ConceptSourceResource2_1Test.java
- omod/pom.xml
- pom.xml
https://issues.openmrs.org/browse/RESTWS-626
> RESTWS-626 Add new property ConceptSource.uniqueId

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ObsResource1_8.java
For the description of the ticket please look at https://issues.openmrs.org/browse/RESTWS-639.
> RESTWS-639: changed getName to getOriginalFileName

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/VisitResource1_9.java
This change introduce possibility to get visits from DB for specific patient only from specified startDatetime
This change was needed here https://issues.openmrs.org/browse/RA-1306
> RA-1306 added fromStartDate param to VisitResource1_9

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_8/ObsComplexValueController1_8.java
https://issues.openmrs.org/browse/RESTWS-642
> RESTWS-642  Handle different views for complex obs

- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/DelegatingCrudResource.java
> RESTWS-669 Representation option after create or update object using rest API.

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ModuleResource1_8.java
- omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_8/ModuleController1_8Test.java
Now able to get version through Module Resource default representation
> RESTWS-645 Added version to Module Resource default representation

- omod-1.10/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_10/TestOrderSubclassHandler1_10.java
- omod-1.11/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_11/DrugIngredientResource1_11.java
- omod-1.12/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_12/OrderSetMemberResource1_12.java
- omod-1.12/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_12/OrderSetResource1_12.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/DrugOrderSubclassHandler1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/TaskActionResource1_8.java
- omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/HivDrugOrderSubclassHandler.java
- omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/SystemInformationResource1_8Test.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/CustomDatatypeHandlerResource1_9.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/CustomDatatypeResource1_9.java
- omod-common/src/main/java/org/openmrs/module/webservices/docs/swagger/SwaggerSpecificationCreator.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/OpenmrsClassScanner.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/BaseDelegatingSubclassHandler.java
- omod-common/src/test/java/org/mockingbird/test/rest/resource/AnimalClassResource_1_9.java
- omod-common/src/test/java/org/mockingbird/test/rest/resource/AnimalResource_1_9.java
- omod-common/src/test/java/org/mockingbird/test/rest/resource/BirdResource_1_9.java
- omod-common/src/test/java/org/mockingbird/test/rest/resource/DuplicateNameAndOrderAnimalResource_1_9.java
- omod-common/src/test/java/org/mockingbird/test/rest/resource/DuplicateNameAnimalResource_1_9.java
- omod-common/src/test/java/org/mockingbird/test/rest/resource/InstantiateExceptionAnimalResource_1_9.java
- omod-common/src/test/java/org/mockingbird/test/rest/resource/UnannotatedAnimalResource.java
Fix formatting with integrated `java-formatter:format`
> Fix formatting

- omod-1.10/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_10/OrderResource1_10.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/AllergyResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ConceptNameResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ModuleActionResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/PatientIdentifierTypeResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ProblemResource1_8.java
- omod-2.1/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_1/ObsResource2_1.java
- omod-common/src/main/java/org/openmrs/module/webservices/docs/swagger/SwaggerSpecificationCreator.java
- omod-common/src/main/java/org/openmrs/module/webservices/docs/swagger/core/property/EnumProperty.java
Issue: https://issues.openmrs.org/browse/GCI-211
> GCI-211 Replace getEnumsAsList with EnumProperty instance

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/TaskActionResource1_8.java
I have Documented TaskActionResource as described in https://issues.openmrs.org/browse/RESTWS-681
> RESTWS-681: Document TaskActionResource

- omod/src/main/webapp/apiDocs.jsp
> [RESTWS-694] Code clean up

- omod/src/main/webapp/apiDocs.jsp
> [RESTWS-693] Arrange resources alphanumerically in Swagger-Ui

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ModuleActionResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ModuleResource1_8.java
[RESTWS-697: Restart dependency modules after upgrading a module](https://issues.openmrs.org/browse/RESTWS-697)
When one upgrades a module if it has any modules that depend on it which have been stopped, after installation they are not restarted.
> RESTWS-697: Restart dependency modules after upgrading a module

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/VisitTypeResource1_9.java
I worked on https://issues.openmrs.org/browse/RESTWS-700
> RESTWS-700 VisitTypeResource to process includeAll parameter

- omod-2.2/pom.xml
- omod-2.2/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/PatientProgramAttributeResource2_2.java
- omod-2.2/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/ProgramAttributeTypeResource2_2.java
- omod-2.2/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/ProgramEnrollmentResource2_2.java
- omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/RestTestConstants2_2.java
- omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/PatientProgramAttributeResource2_2Test.java
- omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/ProgramAttributeTypeResource2_2Test.java
- omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/ProgramEnrollmentResource2_2Test.java
- omod-2.2/src/test/resources/programEnrollmentDataSet.xml
- pom.xml
[Implementing Program Enrollment Attributes](https://issues.openmrs.org/browse/RESTWS-698)
Integrate Program attributes that were implemented in Bahmni core
> Add bahmni program enrollment changes

- omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_2/ConditionController2_2Test.java
Changed 1 file for this task:
* omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_2/ConditionController2_2Test.java
See https://issues.openmrs.org/browse/TRUNK-5350
No? -> figure out why and …
> TRUNK-5350: Add test case for a coded Condition.

- omod-2.2/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/ConditionResource2_2.java
- omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/RestTestConstants2_2.java
- omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_2/ConditionController2_2Test.java
- omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/ConditionResource2_2Test.java
- omod-2.2/src/test/resources/conditionTestDataset.xml
Changed 5 files for this task:
* omod-2.2/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/ConditionResource2_2.java
* omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/RestTestConstants2_2.java
* omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_2/ConditionController2_2Test.java
* omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/ConditionResource2_2Test.java
* omod-2.2/src/test/resources/conditionTestDataset.xml
See https://issues.openmrs.org/browse/TRUNK-5350
No? Unsure? -> [configure your …
> TRUNK-5350: Add test cases for updating Conditions and refactor some logic

- omod-1.10/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_10/DrugOrderSubclassHandler1_10.java
- omod-1.10/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_10/OrderResource1_10.java
- omod-1.10/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_10/TestOrderSubclassHandler1_10.java
- omod-1.10/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_10/OrderController1_10Test.java
Ticket description found [RESTWS-706](https://issues.openmrs.org/browse/RESTWS-706)
> RESTWS-706 Add sorting by dateActivated Or dateStopped to Orders

- omod-1.10/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_10/OrderResource1_10.java
- omod-2.2/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/FulfillerDetails.java
- omod-2.2/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/FulfillerDetailsResource2_2.java
- omod-2.2/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/OrderResource2_2.java
- omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/RestTestConstants2_2.java
- omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/FulfillerDetailsController2_2Test.java
- omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/FulfillerDetailsResource2_2Test.java
- omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/OrderResource2_2Test.java
Ticket:https://issues.openmrs.org/browse/RESTWS-714
Talk: https://talk.openmrs.org/t/adding-order-status-to-orders/17928/36
> Solving RESTWS-714 - Add fulfillerStatus and Orders.fulfillerComment to Order resource

- omod-1.11/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_11/PersonResource1_11.java
- omod-2.2/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/PersonResource2_2.java
- omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/PersonResource2_2Test.java
Adding new attribute to set of return values
Create one simple test case to make sure everything is working
https://issues.openmrs.org/browse/RESTWS-713
Adapted requested changes of: https://github.com/openmrs/openmrs-module-webservices.rest/pull/337
> Solving RESTWS-713 - Add free-text cause of death to Person resource

- omod-1.10/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_10/OrderResource1_10.java
- omod-1.10/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_10/OrderResource1_10Test.java
- omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/FulfillerDetailsResource2_2Test.java
https://issues.openmrs.org/browse/RESTWS-717
> RESTWS-717: Return orderType for Orders

- omod-1.10/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_10/OrderResource1_10.java
- omod-1.10/src/test/java/org/openmrs/module/webservices/rest/web/RestTestConstants1_10.java
- omod-1.10/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_10/OrderController1_10Test.java
https://issues.openmrs.org/browse/RESTWS-718
Added unit tests for order type and care setting filtering
Fetch orders by order type for patient and unit tests
Throw exception for invalid input to order service
> RESTWS-718: Fetch orders by order type for patient

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/TaskActionResource1_8.java
- omod-2.0/src/test/java/org/openmrs/module/webservices/rest/doc/SwaggerSpecificationCreatorTest.java
- omod-2.0/src/test/java/org/openmrs/module/webservices/rest/resource/SubDetails.java
- omod-2.0/src/test/java/org/openmrs/module/webservices/rest/resource/SubDetailsResource.java
- omod-common/src/main/java/org/openmrs/module/webservices/docs/swagger/SwaggerSpecificationCreator.java
Minor fix for [RESTWS-720](https://issues.openmrs.org/browse/RESTWS-720) preventing the core module producing reference errors.
> RESTWS-720: API Docs generating a lot of reference errors

- omod-1.10/src/test/java/org/openmrs/module/webservices/rest/web/RestTestConstants1_10.java
- omod-2.2/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs2_2/OrderSearchHandler2_2.java
- omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/RestTestConstants2_2.java
- omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs2_2/OrderSearchHandler2_2Test.java
https://issues.openmrs.org/browse/RESTWS-715
> RESTWS-715: Order search handler

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ProgramWorkflowResource1_8.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs1_9/EncounterSearchHandler1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/RestTestConstants1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ProgramController1_9Test.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs1_9/EncounterSearchHandler1_9Test.java
- omod-1.9/src/test/resources/encounterWithCodedObs1_9.xml
- omod-2.0/src/test/java/org/openmrs/module/webservices/rest/doc/SwaggerSpecificationCreatorTest.java
- omod-common/src/main/java/org/openmrs/module/webservices/docs/swagger/SwaggerSpecificationCreator.java
https://tickets.pih-emr.org/browse/UHM-3497
> UHM-3497: Added encounter search by obs text and numeric values

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs1_9/EncounterSearchHandler1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/RestTestConstants1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs1_9/EncounterSearchHandler1_9Test.java
- omod-1.9/src/test/resources/encounterWithCodedObs1_9.xml
https://tickets.pih-emr.org/browse/UHM-3497
> UHM-3497: Make encounter search by obs values optional

- omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/DelegatingCrudResourceTest.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/DelegatingCrudResource.java
https://issues.openmrs.org/browse/RESTWS-729
> RESTWS-729: Allow clients to specify a predefined uuid when creating new resources

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/VisitResource1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/VisitController1_9Test.java
Hi @mogoodrich , here is the PR to address our workflow WOR-181 ticket. Thanks.
> RESTWS-732, add the ability to fetch visits by location

- omod-2.2/pom.xml
I'm sorry being slow at seeing this @dkayiwa
> Update openmrsVersion to 2.2.0-alpha

- .github/PULL_REQUEST_TEMPLATE.md
Proposed a Pull Request Format similar to openmrs-core one.
[see](https://issues.openmrs.org/browse/RESTWS-743)
> RESTWS-743 Adding a PR template to this repository

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/VisitAttributeResource1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/VisitAttributeController1_9Test.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/VisitAttributeTypeController1_9Test.java
- omod-1.9/src/test/resources/customTestDataset1_9.xml
I changed the if statement so that maxOccurs is checked to be not null.
I also added a test to verify it.
[Issue](https://issues.openmrs.org/browse/RESTWS-731)
> RESTWS-731 Checking if maxOccurs is not null

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/VisitResource1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/VisitController1_9Test.java
see https://issues.openmrs.org/browse/RESTWS-744
> RESTWS-744: Visit attributes not getting set properly for an existing visit

- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/filter/ContentTypeFilter.java
- omod-common/src/test/java/org/openmrs/module/webservices/rest/web/filter/ContentTypeFilterTest.java
Moved the content-type filtering from a json-whitelisting approach to an xml-blacklisting approach
see https://issues.openmrs.org/browse/RESTWS-742
Also related topic on the security mailing list
No? -> figure out why and add the …
> RESTWS-742 Implement XML content-type blacklisting

- omod-common/src/main/java/org/openmrs/module/webservices/docs/swagger/SwaggerSpecificationCreator.java
Ticket : https://issues.openmrs.org/browse/RESTWS-748
> RESTWS-748: Add support for Subclasses in swagger docs

- omod-common/src/main/java/org/openmrs/module/webservices/docs/swagger/SwaggerSpecificationCreator.java
Ticket : https://issues.openmrs.org/browse/RESTWS-751
> RESTWS-751: Add support of including POST path operations for Subresources

- omod/src/main/webapp/localHeader.jsp
RESTWS-580 HTTP 404 Error on Help form for version 2.14
https://issues.openmrs.org/browse/RESTWS-580
I have fixed HTTP 404 error on help form.  
No? -> figure out why and add the fix to your commit. It is your responsibility to …
> RESTWS-580 : Fixed HTTP 404 Error on Help form

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ConceptResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/DrugResource1_8.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/ConceptReferenceTermResource1_9.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/ProviderResource1_9.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs1_9/ConceptReferenceTermSearchHandler1_9.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs1_9/LocationAttributeSearchHandler1_9.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/ServiceSearcher.java
see https://issues.openmrs.org/browse/RESTWS-705
> RESTWS-705:total count included in AlreadyPaged result

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/VisitResource1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/VisitController1_9Test.java
> RESTWS-664, do not return voided encounters

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/VisitResource1_9.java
> RESTWS-664, prevent concurrent modification exception

- .travis.yml
- omod-1.12/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_12/OrderGroupResource1_12.java
- omod-1.12/src/test/java/org/openmrs/module/webservices/rest/web/RestTestConstants1_12.java
- omod-1.12/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_12/OrderGroupController1_12Test.java
- omod-1.12/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_12/OrderGroupResource1_12Test.java
- omod-1.12/src/test/resources/orderGroupTestDataset.xml
Ticket : https://issues.openmrs.org/browse/RESTWS-680
What i worked on 
- I created the OrderGroup  Resource
- I created test units for my new changes
> RESTWS-680:Added OrderGroup Resouce and added tests

- README.md
Semantic issue on paragraph 63 plus minor coding formatting proposal on line 47
This PR is no related to previous issues (at the time of this commit)
No? -> figure out why and add the fix to your commit. It is your responsibility …
> Semantic issue on paragraph 63

- omod-2.3/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs2_3/OrderSearchHandler2_3.java
- omod-2.3/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs2_3/OrderSearchHandler2_3Test.java
@mogoodrich , here is the corresponding PR for filtering out DISCONTINUE orders. Thanks!
> RESTWS-759, filter out DISCONTINUE orders

- pom.xml
Upgrade jackson-databind from 2.9.10.1 to 2.10.1
> Upgrade jackson-databind from 2.9.10.1 to 2.10.1

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/VisitResource1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/VisitController1_9Test.java
> RA-1695, search visits by visit type

- omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/SearchIndexController2_0.java
- omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/SearchIndexController2_0IntegrationTest.java
- omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/SearchIndexController2_0Test.java
- omod-2.0/src/test/resources/UpdateSearchIndexForObject_testData.xml
- omod-2.0/src/test/resources/UpdateSearchIndexForType_testData.xml
- pom.xml
see https://issues.openmrs.org/browse/RESTWS-766
> RESTWS-766: Add resource for rebuilding the search index.

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/SessionController1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/SessionController1_9Test.java
> RESTWS-767: SessionController does not support custom representations

- omod-1.10/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_10/OrderFrequencyController1_10Test.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/CohortMemberResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/EncounterResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ObsResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/OrderResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs1_8/LocationSearchHandler.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/SessionController1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ConceptController1_8Test.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ConceptController1_9Test.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/DrugController1_9Test.java
- omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_0/PatientAllergyResource2_0.java
- omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/ConceptController2_0Test.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/util/ReflectionUtil.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/ConversionUtil.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/RequestContext.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/RestUtil.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/api/RestService.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/api/impl/RestServiceImpl.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/api/SearchConfig.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/api/SearchQuery.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/BaseDelegatingResource.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/BasePageableResult.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/MetadataDelegatingCrudResource.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/BaseRestController.java
- omod-common/src/main/java/org/openmrs/module/webservices/validation/ValidateUtil.java
Replaced all instances of @should in OpenMRS REST Web Services Module
see https://issues.openmrs.org/browse/TRUNK-5709
- [] I have **added tests** to cover my changes. (If you refactored
No? -> figure out why and add the fix to …
> TRUNK-5709: Replaced all instances of @should

- omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/SearchIndexController2_0.java
- omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/SearchIndexController2_0IntegrationTest.java
https://issues.openmrs.org/browse/RESTWS-766
> RESTWS-766: /searchindexupdate to have response code 204 (NO CONTENT).

- omod-2.2/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/FulfillerDetails2_2.java
- omod-2.2/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/FulfillerDetailsResource2_2.java
- omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_2/FulfillerDetailsController2_2Test.java
- omod-2.3/pom.xml
- omod-2.3/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_3/FulfillerDetails2_3.java
- omod-2.3/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_3/FulfillerDetailsResource2_3.java
- omod-2.3/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/RestTestConstants2_3.java
- omod-2.3/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_3/FulfillerDetailsController2_3Test.java
- omod-2.3/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_3/FulfillerDetailsResource2_3Test.java
> RESTWS-776: Enhance fulfiller details sub resource to allow updating accession number of an order

- omod-1.8/pom.xml
- omod-2.2/pom.xml
- omod-2.2/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/PersonResource2_2.java
- omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_2/PersonController2_2Test.java
see https://issues.openmrs.org/browse/RESTWS-777
> REST-777 Added causeOfDeathNonCoded as the updatable Property in REST

- omod-1.11/pom.xml
- omod-1.12/pom.xml
- omod-2.0/pom.xml
- omod-2.1/pom.xml
- omod-2.2/pom.xml
- omod-2.3/pom.xml
- omod-common/pom.xml
- pom.xml
see https://issues.openmrs.org/browse/RESTWS-782
> RESTWS-782: upgrade org.apache.tomcat from 6.0.18 to 6.0.53

- omod-common/pom.xml
see https://issues.openmrs.org/browse/RESTWS-785
> RESTWS-785: Upgrade evo-inflector from 1.2.1 to 1.2.2

- omod-2.4/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_4/ServerLogController2_4Test.java
- omod-2.4/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_4/ServerLogResource2_4Test.java
see https://issues.openmrs.org/browse/TRUNK-5818
> TRUNK-5818 Enable module devs to write Junit 4 & 5 tests(Replace all ExpectedException Rules and the @Test(expected..)

- omod-common/pom.xml
see https://issues.openmrs.org/browse/RESTWS-784
> RESTWS-784: upgrade joda-time from 2.9.2 to 2.10.6

- integration-tests/pom.xml
see https://issues.openmrs.org/browse/RESTWS-778
> RESTWS-787: Upgrade org.apache.httpcomponents from 4.5.3 to 4.5.12

- omod-common/pom.xml
see https://issues.openmrs.org/browse/RESTWS-783
> RESTWS-783: upgrade swagger-core from 1.5.13 to 1.6.2

- omod-2.4/pom.xml
link: https://issues.openmrs.org/browse/RESTWS-814
> RESTWS-814:Upgrade the rest module to depend on core 2.4.0-alpha

- omod-1.11/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs1_11/LivingPatientSearchHandler1_11.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ModuleActionResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ObsResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/PatientStateResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs1_8/PatientByIdentifierSearchHandler1_8.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/VisitResource1_9.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs1_9/EncounterSearchHandler1_9.java
- omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_0/PatientAllergyResource2_0.java
- omod-2.2/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs2_2/OrderSearchHandler2_2.java
- omod-2.3/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs2_3/OrderSearchHandler2_3.java
see https://issues.openmrs.org/browse/RESTWS-812
> RESTWS-812-Collection.isEmpty() should be used to test for emptiness

- omod-1.12/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_12/OrderGroupResource1_12.java
see https://issues.openmrs.org/browse/RESTWS-811
> RESTWS-811: @Override should be used on overriding and implementing methods

- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/api/impl/RestServiceImpl.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/filter/ContentTypeFilter.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/api/SearchConfig.java
see https://issues.openmrs.org/browse/RESTWS-804
> RESTWS-804: Return of boolean expressions should not be wrapped into an "if-then-else" statement

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ConceptResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ObsResource1_8.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/SystemSettingResource1_9.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/RestUtil.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/api/SearchQuery.java
see https://issues.openmrs.org/browse/RESTWS-797
> RESTWS-797: "if-else" clauses should be enclosed in curly braces

- omod-1.10/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_10/OrderUtil.java
- omod-1.10/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_10/RestConstants1_10.java
- omod-1.11/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_11/RestConstants1_11.java
- omod-1.12/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_12/RestConstants1_12.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/RestConstants1_9.java
see https://issues.openmrs.org/browse/RESTWS-808
> RESTWS-808: utility classes should not have public constructors

- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/RestUtil.java
see https://issues.openmrs.org/browse/RESTWS-806
> RESTWS-806: Resources should be closed

- omod-common/src/main/java/org/openmrs/module/webservices/docs/swagger/SwaggerSpecificationCreator.java
see https://issues.openmrs.org/browse/RESTWS-805
> RESTWS-805: Constructor should not be used to instantiate "String"

- omod-1.12/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_12/DrugResource1_12.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/RelationshipResource1_9.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs1_9/ConceptReferenceTermSearchHandler1_9.java
- omod-2.1/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_1/ConceptSourceResource2_1.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/BaseDelegatingResource.java
see https://issues.openmrs.org/browse/RESTWS-803
> Restws 803: Two branches in a conditional structure should not have exactly the same implementation

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ModuleActionResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ModuleResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/TaskActionResource1_8.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/OpenmrsPathMatcher.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/OpenmrsClassScanner.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/api/impl/RestServiceImpl.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/BaseDelegatingResource.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/BaseDelegatingSubclassHandler.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/DelegatingCrudResource.java
see https://issues.openmrs.org/browse/RESTWS-802?src=confmacro
No? -> figure out why and add the …
> RESTWS-802:Collapsible if statements should be merged

- omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/SearchIndexController2_0.java
**Pull request title** 
RESTWS-798:Parameterized messages should be used for logging
**JiraIssueNumber JiraIssueTitle**
RESTWS-798:Parameterized messages should be used for logging
**Description of what I changed**
Replace use of string concatenation for logging messages with parameterized messages 
**Issue I worked on**
https://issues.openmrs.org/browse/RESTWS-798
No? -> write …
> RESTWS-798:Parameterized messages should be used for logging

- omod-1.10/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_10/RestConstants1_10.java
- omod-1.11/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_11/RestConstants1_11.java
- omod-1.12/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_12/RestConstants1_12.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/RestConstants1_9.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs1_9/LocationAttributeSearchHandler1_9.java
see https://issues.openmrs.org/browse/RESTWS-801
- [ x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.
- [ x] I ran `mvn clean package` right before creating this …
> RESTWS-801:  Modifiers should be declared in the correct order

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/PatientIdentifierResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/UserResource1_8.java
**Pull request title**
RESTWS-794:Unused assignments should be removed
**JiraIssueNumber:JiraIssueTitle**
RESTWS-794:Unused assignments should be removed 
**Description of what I changed**
Remove an unused assignment
**Issue I worked on**
https://issues.openmrs.org/browse/RESTWS-794
added all …
> RESTWS-794:Unused assignments should be removed

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/VisitResource1_9.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/BaseDelegatingSubclassHandler.java
https://issues.openmrs.org/projects/RESTWS/issues/RESTWS-793
I removed both empty statements listed in the open issue. …
> REST-793:remove empty statements

- omod-2.4/pom.xml
- omod-2.4/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/jupiter/MainResourceControllerTest.java
- omod-2.4/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/jupiter/RestControllerTestUtils.java
- omod-2.4/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_4/ServerLogController2_4Test.java
- omod-2.4/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_4/ServerLogResource2_4Test.java
- pom.xml
see https://issues.openmrs.org/browse/TRUNK-5818
> TRUNK-5818: Enable module devs to write Junit 4 & 5 tests

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/ObsResource1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/ConversionUtil1_9Test.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ObsController1_9Test.java
…Encounter and one or more the nested obs is of type "valueLocation" or "valueDrug"
> RESTWS-816: ObsResource to not fail conversions of obs drugs and obs locations.

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/PatientIdentifierResource1_8.java
**Pull request title**
RESTWS-810:Bolean expressions should not be gratuitous
**JiraIssueNumber : JiraIssueTitle**
RESTWS-810:Bolean expressions should not be gratuitous
**Description of what I changed**
Removal of unnecessary checking.
**Issue I worked on**
https://issues.openmrs.org/browse/RESTWS-810
No? -> write tests and add them to this commit `git add . && git commit …
> RESTWS-810:Bolean expressions should not be gratuitous

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/SessionController1_9.java
see https://issues.openmrs.org/browse/RESTWS-767
> Restws 767 2

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/SessionController1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/SessionController1_9Test.java
Added current user selected location and provider to the session
see https://issues.openmrs.org/projects/RESTWS/issues/RESTWS-763
No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your …
> RESTWS-763: Add current provider to the session

- integration-tests/pom.xml
- omod-1.10/pom.xml
- omod-1.11/pom.xml
- omod-1.12/pom.xml
- omod-1.8/pom.xml
- omod-1.9/pom.xml
- omod-2.0/pom.xml
- omod-2.1/pom.xml
- omod-2.2/pom.xml
- omod-2.3/pom.xml
- omod-2.4/pom.xml
- omod-common/pom.xml
- omod/pom.xml
- pom.xml
Fixing the snapshot version cc @dkayiwa
> Fixing the snapshot version

- omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_0/AlertRecipientResource2_0.java
- omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_0/AlertResource2_0.java
- omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/AlertController2_0Test.java
- omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/AlertRecipientController2_0Test.java
- omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_0/AlertRecipientResource2_0Test.java
- omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_0/AlertResource2_0Test.java
Added REST resource for managing OpenMRS Alerts.
PR with documentation: [https://github.com/openmrs/openmrs-contrib-rest-api-docs/pull/143](https://github.com/openmrs/openmrs-contrib-rest-api-docs/pull/143)
see https://issues.openmrs.org/browse/RESTWS-823 …
> RESTWS-823: Add REST resource for Alert Management

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/PatientResource1_8.java
- omod-2.4/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_4/PatientController2_4Test.java
Extended PatientResource to allow finding duplicated Patients
see https://issues.openmrs.org/browse/RESTWS-842
No? …
> RESTWS-842: Extend PatientResource to allow finding Patients to be merged

- omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_0/ConceptProposalResource2_0.java
- omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/ConceptProposalController2_0Test.java
- omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_0/ConceptProposalResource2_0Test.java
Added REST resource for ConceptProposal management
see https://issues.openmrs.org/browse/RESTWS-830
PR with documentation: https://github.com/openmrs/openmrs-contrib-rest-api-docs/pull/159
No? -> figure out why and add the fix to …
> RESTWS-830: Add REST resource for ConceptProposal management

- omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/ImplementationIdController2_0.java
- omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/converter/openmrs2_0/ImplementationIdConverter2_0.java
- omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/ImplementationIdController2_0Test.java
Added ImplementationIdController2_0 for Implementation ID management.
see https://issues.openmrs.org/browse/RESTWS-833
PR with documentation: https://github.com/openmrs/openmrs-contrib-rest-api-docs/pull/163
No? -> figure out why …
> RESTWS-833: Add REST resource for Implementation ID management

- omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/LocaleAndThemeConfigurationController2_0.java
- omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/converter/openmrs2_0/LocaleAndThemeConfigurationConverter2_0.java
- omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/wrapper/LocaleAndThemeConfiguration.java
- omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/LocaleAndThemeConfigurationController2_0Test.java
Added resource for default locale and default theme management.
see https://issues.openmrs.org/browse/RESTWS-846
PR with documentation: https://github.com/openmrs/openmrs-contrib-rest-api-docs/pull/166
No? -> figure out why and …
> RESTWS-846: Add LocaleAndThemeConfigurationController2_0

- .github/workflows/maven.yml
- README.md
- omod/pom.xml
- pom.xml
https://issues.openmrs.org/browse/RESTWS-848  cc @dkayiwa  @ibacher  @gracepotma
jacoco and coverals are configured in root pom pluginmanagement
> RESTWS-848:Check if Coveralls is working with REST Repo

- .github/workflows/maven.yml
- README.md
- omod/pom.xml
- pom.xml
Reverts openmrs/openmrs-module-webservices.rest#499
> Revert "RESTWS-848:Check if Coveralls is working with REST Repo"

- integration-tests/pom.xml
- omod-1.10/pom.xml
- omod-1.11/pom.xml
- omod-1.12/pom.xml
- omod-1.8/pom.xml
- omod-1.9/pom.xml
- omod-2.0/pom.xml
- omod-2.1/pom.xml
- omod-2.2/pom.xml
- omod-2.3/pom.xml
- omod-2.4/pom.xml
- omod-common/pom.xml
- omod/pom.xml
- pom.xml
> updating next development version

- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/VisitAttributeTypeController1_9Test.java
Added an end point visit attribute type search test
see https://issues.openmrs.org/browse/RESTWS-852
- [ x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.
- [ x] I …
> RESTWS-852: End point visit attribute type search test

- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/VisitTypeController1_9Test.java
Added end point visit search test
see https://issues.openmrs.org/browse/RESTWS-851
- [ x] I have **added tests** to cover my changes. (If you refactored
- [x ] I ran …
> RESTWS-851: End point visit type search test

- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/VisitController1_9Test.java
Added end point visit search test
see https://issues.openmrs.org/browse/RESTWS-850
- [ x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.
- [x ] I ran `mvn clean …
> RESTWS-850: End point visit search test

- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ObsController1_9Test.java
Added End point obs search test
see https://issues.openmrs.org/browse/RESTWS-858
- [x ] My pull request only contains **ONE single commit**
- [x ] I ran `mvn clean …
> RESTWS-858: End point obs search test

- omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/ConceptAttributeController2_0Test.java
see https://issues.openmrs.org/browse/RESTWS-855
- [x ] My pull request only contains **ONE single commit**
- [x ] I ran `mvn clean package` right before creating this …
> RESTWS-855: End point concept attribute search by uuid test

- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/FormResourceController1_9Test.java
see https://issues.openmrs.org/browse/RESTWS-860
- [x ] My pull request only contains **ONE single commit**
- [x ] I ran `mvn clean package` right before creating this …
> RESTWS-860: End point form resource search by uuid test

- omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/ConceptAttributeTypeController2_0Test.java
- omod-2.0/src/test/resources/conceptAttributeDataSet.xml
Added test for updating  ` ConceptAttributeType
`
see https://issues.openmrs.org/browse/RESTWS-857
> RESTWS-857: Concept Attribute Types Update Test Endpoint

- omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/ClearDbCacheController2_0.java
- omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/ClearDbCacheController2_0Test.java
- omod-2.0/src/test/resources/hibernate.default.properties
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/RestUtil.java
[RESTWS-866](https://issues.openmrs.org/browse/RESTWS-866) - Add REST endpoint to invalidate the Hibernate L2 cache
No? -> figure out why and add the fix to your commit. It is your …
> RESTWS-866: Add REST endpoint to invalidate the Hibernate L2 cache.

- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/FormResourceController1_9Test.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ProviderController1_9Test.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/VisitAttributeTypeController1_9Test.java
Added end point update provider test
see https://issues.openmrs.org/browse/RESTWS-853
- [x ] I ran `mvn clean …
> RASTWS-853: End point update provider test

- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/FormResourceController1_9Test.java
see https://issues.openmrs.org/browse/RESTWS-862
- [x ] I ran `mvn clean package` right before creating this …
> RESTWS-862: End point update form test

- omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/ConceptAttributeTypeController2_0Test.java
see https://issues.openmrs.org/browse/RESTWS-868
- [x ] I have **added tests** to cover my changes. (If you refactored
No? -> write tests and add them to this commit `git add . && git commit …
> REST-868: End point concept attribute type search uuid

- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ObsController1_9Test.java
- omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_2/ObsController2_2Test.java
- omod-2.2/src/test/resources/obsDataSet2_2.xml
Created `new class` in `obs 2.2` since the **getRevisionObs()** starts to work in` 2.1 OpenMRS_Version` which helps to get updated properties of obs
Added `Update Obs test` which only modifies properties in the request.
see https://issues.openmrs.org/browse/RESTWS-861
> RESTWS-861:Obs Update Test endpoint

- omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/ConceptAttributeTypeController2_0Test.java
I added and end point test to delete concept attribute type
[RESTWS-875](https://issues.openmrs.org/browse/RESTWS-875)
No? -> figure out why and add the fix to your …
> RESTWS-875: Fix End point- Concept attribute types delete test

- omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/ConceptAttributeTypeController2_0Test.java
Added retire Test for Concept attribute type ~ Endpoint
see https://issues.openmrs.org/browse/RESTWS-877
> RESTWS-877: Concept attribute type retire test | Endpoint

- omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/ClearDbCacheController2_0.java
- omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/ClearDbCacheController2_0Test.java
https://issues.openmrs.org/browse/RESTWS-881
> RESTWS-881 - Clearing DB cache should not fail when an entity is not found

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/ObsTreeResource1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ObsTreeController1_9Test.java
- omod-1.9/src/test/resources/obsTreeDataset.json
- omod-1.9/src/test/resources/obsTreeDataset.xml
see https://issues.openmrs.org/browse/RESTWS-882
> RESTWS-882 Test Result Trees Driven by Concept Sets

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs1_8/FormSearchHandler1_8.java
- omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs1_8/FormSearchHandlerTest.java
- omod-1.8/src/test/resources/formTestDataSet.xml
- Created  FormSearchHandler class
- Added formTestDataSet.xml file in the test resource
- Created FormSearchHandlerTest class and carried out units on the search parameters 
see https://issues.openmrs.org/browse/RESTWS-880
No? …
> RESTWS-880: Add support to only return published forms from the backend

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/SessionController1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/SessionController1_9Test.java
Does what it says in the title. This allows you to actually log out via the REST API.
see https://issues.openmrs.org/browse/RESTWS-887
No? -> figure out why and add the fix to your commit. It is your responsibility to make sure …
> RESTWS-887: Session endpoint should expire the cookie on delete

- omod-2.2/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/ProgramAttributeTypeResource2_2.java
- omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/ProgramAttributeTypeResource2_2Test.java
- omod-2.2/src/test/resources/programEnrollmentDataSet.xml
[RESTWS-888](https://issues.openmrs.org/browse/RESTWS-888) Add support for program attribute of type "concept" for ProgramAttributeTypeResource
> Bindu | RESTWS-888 | Add support for program Attribute Type Concept

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs1_8/UserSearchHandler1_8.java
> RESTWS-889 - UserSearchHandler1_8 needs to support OpenMRS 2.6.*

- omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_0/PatientAllergyResource2_0.java
- omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/PatientAllergyController2_0Test.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/response/NoContentFoundException.java
The main objective of this pull request is to ensure that while fetching allergies for a patient with no allergies, the response body should be empty and the status code should be [HTTP 204 NO CONTENT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204) [as per the discussion](https://talk.openmrs.org/t/newly-registered-patients-default-allergy-value/37228/19).
- I added a new class called `NoContentFoundException` that extends the `ResponseException` class.
- I added the @ResponseStatus annotation whose value i set to HttpStatus' `HTTP 204 No Content`.
- I then ensured that in the `doGetAll` method in the `PatientAllergyResource2_0` class throws the  `NoContentFoundException` whenever Allergies is `unknown`
see https://issues.openmrs.org/browse/RESTWS-895
(the number above, …
> Restws 895: Ensure fetching Allergies for a newly created patient returns HTTP 204-No Content Response Status code

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ConceptReferenceController1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ConceptReferenceController1_9Test.java
- omod-common/src/main/java/org/openmrs/module/webservices/rest/SimpleObject.java
Adds the endpoint `/conceptreferences` which takes a parameter, `references`, which is a list of concept UUIDs or mappings and returns a map of key-value pairs from UUIDs and mappings -> the underlying concept.
see https://issues.openmrs.org/browse/RESTWS-894
added all formatting changes to my …
> RESTWS-894: Add a ConceptReferences API endpoint

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/SessionController1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/SessionController1_9Test.java
Removes `sessionId` from the output of the session endpoint.
see https://issues.openmrs.org/browse/RESTWS-903
No? …
> RESTWS-903: Session endpoint should not return sessionId

- integration-tests/pom.xml
- omod-1.10/pom.xml
- omod-1.11/pom.xml
- omod-1.12/pom.xml
- omod-1.8/pom.xml
- omod-1.9/pom.xml
- omod-2.0/pom.xml
- omod-2.1/pom.xml
- omod-2.2/pom.xml
- omod-2.3/pom.xml
- omod-2.4/pom.xml
- omod-common/pom.xml
- omod/pom.xml
- pom.xml
Changed the Snapshot version from 2.30 - 2.39.0.
> Fixed the SNAPSHOT version  From 2.30.0 to 2.39.0

- omod-2.2/pom.xml
- omod-2.2/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/ConditionResource2_2.java
- omod-2.2/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/DiagnosisResource2_2.java
- omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_2/ConditionController2_2Test.java
- omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_2/DiagnosisController2_2Test.java
- omod-2.2/src/test/resources/conditionTestDataset.xml
- omod-2.4/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/RestTestConstants2_4.java
This implements two endpoints that search for the condition of a patient and diagnosis of a patient.
Created search handlers for condition and diagnosis.
see https://issues.openmrs.org/browse/RESTWS-900
No? -> figure out why and …
> RESTWS-900: Get conditions or patient-diagnosis by patient

- .github/PULL_REQUEST_TEMPLATE.md
Remove "My pull request only contains ONE single commit" checkbox from PR template
see https://issues.openmrs.org/browse/RESTWS-906
No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your …
> RESTWS-906: Remove "My pull request only contains ONE single commit" checkbox from PR template

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ModuleResource1_8.java
- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/TaskDefinitionResource1_8.java
- omod-common/src/main/java/org/openmrs/module/webservices/docs/swagger/SwaggerSpecificationCreator.java
- Refactored the code to compare strings using .equals()
- no new tests were added as the existing code was refactored
see https://issues.openmrs.org/browse/RESTWS-813
> RESTWS-813: Strings should not be compared by using == or !=

- omod-common/pom.xml
> RESTWS-912: Update Version of Joda Time Library

- omod-common/src/main/java/org/openmrs/module/webservices/rest/web/ConversionUtil.java
- omod-common/src/test/java/org/openmrs/module/webservices/rest/web/ConversionUtilTest.java
Fixed an issue in the `convertMap` method where the converter properties are set twice in cases where the converter is an instance of `DelegatingResourceHandler`.
see https://issues.openmrs.org/browse/RESTWS-901
> RESTWS-901: Call property setters only once on map conversion

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/SessionController1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/SessionController1_9Test.java
return current session details after updating session properties by calling 'get()' method. 
see https://issues.openmrs.org/browse/RESTWS-919
> RESTWS-919: POST request to /session endpoint should return current session

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/EncounterResource1_9.java
see https://issues.openmrs.org/browse/RESTWS-930
> RESTWS-930: Avoid appending extraneous encounter providers to encounter

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/VisitResource1_9.java
RESTWS-932: Visit Search: add "toStartDate" parameter
See:
https://openmrs.atlassian.net/browse/RESTWS-931
https://openmrs.atlassian.net/browse/RESTWS-932
> RESTWS-931: Visit Search: add support to include parent locations

- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/SessionController1_9.java
- omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/SessionController2_0.java
- omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/SessionController2_0Test.java
- omod-2.0/src/test/resources/sessionControllerTestDataset.xml
see https://issues.openmrs.org/browse/RESTWS-946
> RESTWS-946: /session endpoint throws an error if user doesn't have Get Providers privilege

- omod-2.5/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_5/DiagnosisResource2_5.java
- omod-2.5/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_5/DiagnosisResource2_5Test.java
This is a followup of https://github.com/openmrs/openmrs-module-webservices.rest/pull/609. It basically introduces setters which fixes an NPE.
The issue:
see https://issues.openmrs.org/browse/RESTWS-939
> Explicitly define form field path property setters

- omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ObsResource1_8.java
- omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/ObsTreeResource1_9.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ObsTreeController1_9Test.java
- omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/ObsResource1_9Test.java
- omod-1.9/src/test/resources/obsTreeDataset.json
[see https://issues.openmrs.org/browse/RESTWS-](https://openmrs.atlassian.net/browse/RESTWS-967)
> RESTWS-967: Return Obs of type "Date" in "yyyy-MM-dd" format

- omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/AddressTemplateController2_0.java
- omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/NameTemplateController2_0.java
- omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/helper/LayoutTemplateProvider.java
RESTWS-938 Add an API to retrieve NameTemplate by id
Straight refactoring of `AddressTemplateController2_0.java` and `NameTemplateController2_0.java` to extract duplicate code. 
This refactoring is a prerequisite before making breaking changes to the NameTemplate controller in a subsequent PR.
Supersedes PR #641.
see https://issues.openmrs.org/browse/RESTWS-938
_(straight refactoring of existing code - no new tests required)_ …
> RESTWS-938: Refactor common code in AddressTemplate and NameTemplate controllers

- omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/AddressTemplateController2_0.java
- omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/helper/LayoutTemplateProvider.java
- omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/helper/LayoutTemplateRepresentation.java
- omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_0/NameTemplateResource2_0.java
The purpose of this change was:
1) apply locale-specific translations to the namemapping values when retrieving nametemplates (and consequently the dislplayText values of the `nametemplate.lines()` property, since these displayText values are derived from the namemapping values).
2) make the API implementation consistent for nametemplate and addresstemplate APIs
Changes applied:
1) Refactor `LayoutTemplateProvider` class by splitting out representation description methods into a separate `LayoutTemplateRepresentation` class.
2) Fix `LayoutTemplateProvider` to apply locale-specific translations to namemapping values.
3) Amend `AddressTemplateController2_0` to use a standard `BaseDelegatingConverter<AddressTemplate>` implementation when generating a REST response, as opposed to the custom …
> (fix) RESTWS-972 translate nametemplate namemappings

- omod-2.7/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_7/ConceptReferenceRangeResource2_7.java
- omod-2.7/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_7/RestConstants2_7.java
- omod-2.7/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_7/ConceptReferenceRangeController2_7Test.java
- omod-2.7/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_7/ConceptReferenceRangeResource2_7Test.java
see https://openmrs.atlassian.net/browse/RESTWS-976
> RESTWS-976 get reference range for a concept and patient

- omod-2.5/pom.xml
- omod-2.5/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_5/ConceptReferenceRangeResource2_5.java
- omod-2.5/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_5/RestConstants2_5.java
- omod-2.5/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_5/ConceptReferenceRangeController2_5Test.java
- omod-2.5/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_5/ConceptReferenceRangeResource2_5Test.java
see https://openmrs.atlassian.net/browse/RESTWS-977
> RESTWS-977 Add a conceptreferencerange endpoint for 2.6 and below

- omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_0/UserResource2_0.java
- omod-2.2/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/UserResource2_2.java
> RESTWS-982: User Resource should support "email" property of User

- bamboo-specs/bamboo.yaml
> Fixed 'Release scripts' repository in bamboo.yaml.

- omod/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ObsResource1_8.java
see https://issues.openmrs.org/browse/RESTWS-995
> RESTWS-995: Obs: allow "valueComplex" to be creatable
