openmrs/openmrs-module-webservices.rest

omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/PatientResource1_8.java, omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_8/EncounterController1_8Test.java
Added unit test to confirm that fix for https://issues.openmrs.org/browse/RESTWS-460, also allows submitting encounters with patient properties other than the uuid.
=> RESTWS-459: Added unit test

omod-common/src/main/java/org/openmrs/module/webservices/rest/web/response/ConversionException.java
If we can assume that a {{ConversionException}} is always caused by wrong data in the request we could just change the request type to 400
=> REST-496: Handle internal errors gracefully, make them self-explanatory

omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ConceptDescriptionResource1_8.java, omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ConceptResource1_8.java, omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/FieldAnswerResource1_8.java, omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/FormFieldResource1_8.java, omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/PersonResource1_8.java, omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/UserResource1_8.java, omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/ConceptReferenceTermMapResource1_9.java, omod-common/src/main/java/org/openmrs/module/webservices/rest/web/ConversionUtil.java, omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/BaseDelegatingResource.java, omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/BaseDelegatingSubclassHandler.java, omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/DataDelegatingCrudResource.java, omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/DelegatingSubResource.java, omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/MetadataDelegatingCrudResource.java
https://issues.openmrs.org/browse/RESTWS-536
Audit info attributes are obtained in a single utilitty method and used in the base classes of resources. There is no a single ancestor for all resources, that's why I had to put it in a utility class.
=> RESTWS-536: refactoring of getAuditInfo

omod-common/pom.xml, omod-common/src/main/java/org/openmrs/module/webservices/rest/web/ConversionUtil.java, omod-common/src/test/java/org/openmrs/module/webservices/rest/web/ConversionUtilTest.java
**Issue**: [RESTWS-419](https://issues.openmrs.org/browse/RESTWS-419)
**Fix**: Replace the the non ISO8601 `SimpleDateFormat` in Java with the `DateTime` class parser which is a part of the [Joda-Time] (http://www.joda.org/joda-time/) public library. This parses ISO compliant dates correctly and fixes the issue where TimeZones were being dropped.
A relevant Unit Test has also been added
=> Fix for: RESTWS-419 - WSD-DATE date parsing not quite ISO8601 compatible

omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ConceptResource1_8.java, omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ConceptController1_8Test.java
This pull request fixes ClassCastException by changing argument type. Clearing list and adding mappings one by one instead of straightforward setting new Set is necessary to avoid hibernate errors with deleting orphans.
=> RESTWS-599 Fix updating concept's mappings

omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ConceptResource1_8.java, omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ObsResource1_8.java, omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ConceptController1_8Test.java
This PR contains #216 which was reverted in #218 + it fixes bug in ObsResource1_8 save method, which  sometimes caused [lazy initialization errors](https://ci.openmrs.org/browse/RESTWS-RESTWS-JOB1-583/test/case/77595067), and was reason why #216 was reverted in first place.
=> RESTWS 599 fix updating concept's mapping and ObsResource save method

omod/src/main/webapp/apiDocs.jsp
This PR removes the online validation from the OpenAPI documentation. The important line is:
```js
validatorUrl: null
```
All other changes are just formatting.
=> RESTWS-592: Remove Online OpenAPI Spec Validation

omod/src/main/webapp/apiDocs.jsp
Previously, Swagger UI was including its own copy of jQuery (and preventing OpenMRS from including a copy). This caused code generated by the header in the legacy UI to fall over💥.
This PR changes things so that the default jQuery provided by the legacy UI is used instead. However, since Swagger UI expects the 💲 variable to exist, we also have to do the following hack because the legacy UI uses `jQuery.noConflict()`:
```js
var $ = jQuery; 
```
=> 💲 RESTWS-579: Ensure both legacy UI and Swagger can access jQuery

omod-common/src/main/java/org/openmrs/module/webservices/rest/web/api/impl/RestServiceImpl.java, omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/BaseDelegatingResource.java, omod-common/src/test/java/org/openmrs/module/webservices/rest/test/OpenmrsProfileRule.java
replace try/catch block used to check if SearchHandler supports given
OpenMRS
version by an if statement and the ModuleUtil method returning a boolean if
version is supported.
see https://issues.openmrs.org/browse/RESTWS-609
=> RESTWS-609 Cleanup smell of exception as control flow using ModuleUtil

omod-common/src/main/java/org/openmrs/module/webservices/rest/web/api/impl/RestHelperServiceImpl.java
Fixed missing/wrong javadocs in RestHelperServiceImpl and added a missing Override annotation to getPatients()
=> Fix javadocs in RestHelperServiceImpl

.travis.yml, README.md, omod-common/pom.xml, omod/pom.xml, pom.xml
* add jacoco maven plugin for generating coverage reports
* add coveralls maven plugin to send jacoco reports to coveralls.io
* add travis after_success command to send jacoco reports to coveralls.io after
successful builds
* jacoco and coverals are configured in root pom pluginmanagement
* added coverage badge to README
* jacoco only generates coverage for omod and omod-common for now since omod-1.8, omod-1.9, ...
do not have a build section in their pom.xml
see https://issues.openmrs.org/browse/RESTWS-584
=> RESTWS-584 Add jacoco + coveralls.io test coverage

omod-1.10/pom.xml, omod-1.11/pom.xml, omod-1.12/pom.xml, omod-1.8/pom.xml, omod-1.9/pom.xml, omod-2.0/pom.xml
* add build/plugin section to the maven submodules omod-1.8, omod-1.9,...
so coverage reports are also generated for them
see https://issues.openmrs.org/browse/RESTWS-584
=> RESTWS-584 Add coverage to omod-1.8, ... modules

pom.xml
formatter should not enforce line endings.
line endings are specific to the devs environment and are handled by git on checkout.
see https://issues.openmrs.org/browse/RESTWS-618
=> RESTWS-618 Formatter config forces CRLF line endings

omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/api/SearchConfig.java, omod-common/src/test/java/org/openmrs/module/webservices/rest/web/resource/api/SearchConfigTest.java
* add javadocs to SearchConfig
* add test class for SearchConfig
* move validation of parameters in constructor before setting the instance
properties. so we fail fast if a param is invalid (also fixes a NPE if given a
null supportedOpenmrsVersions).
* simplify SearchConfig.equals()
id, supportedResource, supportedOpenmrsVersion do not have to be tested for
null since they cannot be null (see constructors).
replace obj == null and obj.getClass() != getClass() with instanceof operator
see https://issues.openmrs.org/browse/RESTWS-619
=> RESTWS-619 Add SearchConfigTest

omod-common/src/main/java/org/openmrs/module/webservices/rest/web/api/impl/RestServiceImpl.java, omod-common/src/main/resources/webModuleApplicationContext.xml, omod-common/src/test/java/org/mockingbird/test/rest/resource/DuplicateNameAndOrderMockingBirdFantasyResource.java, omod-common/src/test/java/org/mockingbird/test/rest/resource/DuplicateNameMockingBirdFantasyResource.java, omod-common/src/test/java/org/mockingbird/test/rest/resource/MockingBirdFantasyNameResource.java, omod-common/src/test/java/org/mockingbird/test/rest/resource/MockingBirdFantasyResource.java, omod-common/src/test/java/org/mockingbird/test/rest/resource/UnannotatedMockingBirdFantasyResource.java, omod-common/src/test/java/org/openmrs/module/webservices/rest/web/api/impl/RestServiceImplTest.java
* add dependency for OpenmrsClassScanner to RestServiceImpl and inject via xml
using the factory method on OpenmrsClassScanner.getInstance() which returns the
singleton instance
* add first tests for getResourceByName by mocking the
OpenmrsClassScanner.getClasses
see https://issues.openmrs.org/browse/RESTWS-623
=> RESTWS-623 Make RestServiceImpl.getResourceByName testable

omod-common/src/main/java/org/openmrs/module/webservices/rest/web/api/impl/RestServiceImpl.java, omod-common/src/test/java/org/mockingbird/test/Animal.java, omod-common/src/test/java/org/mockingbird/test/Bird.java, omod-common/src/test/java/org/mockingbird/test/Cat.java, omod-common/src/test/java/org/mockingbird/test/HibernateProxyMockingBird.java, omod-common/src/test/java/org/mockingbird/test/MockingBird.java, omod-common/src/test/java/org/mockingbird/test/rest/resource/AnimalResource_1_9.java, omod-common/src/test/java/org/mockingbird/test/rest/resource/BirdResource_1_9.java, omod-common/src/test/java/org/mockingbird/test/rest/resource/CatResource_1_9.java, omod-common/src/test/java/org/mockingbird/test/rest/resource/DuplicateNameAndOrderMockingBirdResource_1_9.java, omod-common/src/test/java/org/mockingbird/test/rest/resource/DuplicateNameMockingBirdResource_1_9.java, omod-common/src/test/java/org/mockingbird/test/rest/resource/MockingBirdNameResource_1_9.java, omod-common/src/test/java/org/mockingbird/test/rest/resource/MockingBirdResource_1_11.java, omod-common/src/test/java/org/mockingbird/test/rest/resource/MockingBirdResource_1_9.java, omod-common/src/test/java/org/mockingbird/test/rest/resource/UnannotatedMockingBirdResource.java, omod-common/src/test/java/org/openmrs/module/webservices/rest/web/api/impl/RestServiceImplTest.java
* add fake/test domain object MockingBird
* rename MockingBirdFantasyResource to MockingBirdResource and use
MockingBird.class in supportedClass
* add fake/test domain objects Animal/Bird/HibernateProxyMockingBird/Cat
to establish a hierarchy needed for tests of
getResourceBySupportedClass()
* add fake/test Resources for Animal/Bird/Cat
* rename fake/test Resource classes to fit openmrs style with suffix of
supportedOpenmrsVersion
* add tests for getResourceBySupportedClass()
=> Add test for RestServiceImpl.getResourceBySupportedClass

omod-common/src/main/java/org/openmrs/module/webservices/rest/web/api/impl/RestServiceImpl.java, omod-common/src/test/java/org/openmrs/module/webservices/rest/web/api/impl/RestServiceImplTest.java
* move searchhandler tests to bottom to follow order of methods in RestServiceImpl
* add javadoc describing the logic behind finding the SearchHandler
* add tests to cover all cases
=> Add tests for RestServiceImpl.getSearchHandler(name, params)

omod-common/src/main/java/org/openmrs/module/webservices/rest/web/api/RestService.java, omod-common/src/main/java/org/openmrs/module/webservices/rest/web/api/impl/RestServiceImpl.java, omod-common/src/test/java/org/openmrs/module/webservices/rest/web/api/impl/RestServiceImplTest.java
and getAllSearchHandlers
* add tests to RestServiceImpl.getSearchHandlers
* add tests to RestServiceImpl.getAllSearchHandlers
* adjust test of RestServiceImpl.getSearchHandler to match style used in
all other tests
* fix javadocs for getAllSearchHandlers in RestServiceImpl and RestService
=> Add tests to RestServiceImpl.getSearchHandlers

omod-common/src/main/java/org/openmrs/module/webservices/rest/web/api/impl/RestServiceImpl.java, omod-common/src/test/java/org/mockingbird/test/rest/resource/InstantiateExceptionAnimalResource_1_9.java, omod-common/src/test/java/org/openmrs/module/webservices/rest/web/api/impl/RestServiceImplTest.java
* add a new fake Resource to be able to test
failure of instantiating a new Resource when initializing the
resource cache via initialize()
establishing tests first so it will be safe to work on issue https://issues.openmrs.org/browse/RESTWS-612
=> Add tests for RestServiceImpl.initialize()

omod-common/src/main/java/org/openmrs/module/webservices/rest/web/api/impl/RestServiceImpl.java
two nested classes with almost identical implementation where used as a wrapper
class so two strings could be used as keys to the maps holding SearchHandlers.
first string holds the supported resource of the SearchHandler and second is
either the id or a parameter of the SearchHandler.
* renamed one of them to CompositeSearchHandlerKey
* first property stays supportedResource, second property is simply
secondKey which is once populated with the SearchHandler id and
once with the parameter names.
* use instanceof in equals to check for null and if obj is of the same class
see https://issues.openmrs.org/browse/RESTWS-612
=> RESTWS-612 Merge inner wrapper composite key classes into one

omod-common/src/main/java/org/openmrs/module/webservices/rest/web/api/impl/RestServiceImpl.java, omod-common/src/main/java/org/openmrs/module/webservices/rest/web/response/UnknownResourceException.java, omod-common/src/test/java/org/openmrs/module/webservices/rest/web/api/impl/RestServiceImplTest.java
https://issues.openmrs.org/browse/RESTWS-587
=> RESTWS-587 Should return 404 when a resource doesn't exist (not 500)

omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_8/ObsComplexValueController1_8.java, omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ObsResource1_8.java, omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/EncounterController1_9Test.java, omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ObsController1_9Test.java, omod-1.9/src/test/resources/customConceptDataset1_9.xml, omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/EncounterController2_0Test.java, omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/DelegatingCrudResource.java, omod-common/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/MainResourceControllerTest.java
Test now reproduces issue, so i was able to do some fix attempt.
I've removed line `270` at `ObsResource1_8`, because that was obviously reason why child `groupMembers` was null (every `groupMembers` objects' `groupMembers` were wiped).
=> RESTWS-636 - groupMembers in obs groupMembers fix

omod-common/src/main/java/org/openmrs/module/webservices/docs/swagger/SecurityScheme.java, omod-common/src/main/java/org/openmrs/module/webservices/docs/swagger/SwaggerSpecificationCreator.java
We were not conforming to the [**`Security Definitions Object`** spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#security-definitions-object). This PR brings us up to spec by essentially applying the following change:
```diff
{
swagger: "2.0",
// stuff that probably isn't relevant
securityDefinitions: {
+    basicAuth: {
type: "basic",
description: "HTTP basic access authentication using OpenMRS username and password"
+    }
},
// stuff that probably isn't relevant
}
```
Thanks to @mhawila, @teleivo and @dkayiwa.
<details> 
<summary><b>References</b></summary>
&nbsp;&nbsp;👉 <a href="https://talk.openmrs.org/t/openmrs-js-swagger-client-issue/10422">Talk thread</a><br/>
&nbsp;&nbsp;👉 <a href="https://github.com/swagger-api/swagger-js/issues/892">GitHub …
=> RESTWS-650: Correct securityDefinitions Object In OpenAPI Spec

omod-common/src/main/java/org/openmrs/module/webservices/docs/swagger/OperationEnum.java, omod-common/src/main/java/org/openmrs/module/webservices/docs/swagger/SwaggerSpecificationCreator.java
Adds GET operation to root path of a resource, when the resource does not have
a getAll or a custom search handler, but has got doSearch implemented
=> RESTWS-561 Document Basic Search

omod-common/src/main/java/org/openmrs/module/webservices/docs/swagger/SwaggerSpecificationCreator.java
Change descriptions of optional search parameters to the format:
> "Must be used with <requiredParam, ... and requiredParam>"
=> RESTWS-600 Fix description of optional search params

omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/SystemInformationResource1_8.java, omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/SystemInformationResource1_8Test.java
Implemented REST part for SystemInfo.
https://issues.openmrs.org/browse/RESTWS-665
=> RESTWS-665 : SystemInfo REST implementation

omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/TaskActionResource1_8.java, omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/TaskDefinitionResource1_8.java, omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/MockTaskServiceWrapper.java, omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/RestTestConstants1_8.java, omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_8/TaskActionController1_8Test.java, omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_8/TaskDefinitionController1_8Test.java, omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/TaskDefinitionResource1_8Test.java, omod-common/src/main/java/org/openmrs/module/webservices/helper/TaskAction.java, omod-common/src/main/java/org/openmrs/module/webservices/helper/TaskServiceWrapper.java
Created TaskDefinitionResource1_8 for the task REST implementation
=> [RESTWS-673] Scheduler REST Implementation 

omod-common/src/main/java/org/openmrs/module/webservices/docs/swagger/SwaggerSpecificationCreator.java, omod/src/test/java/org/openmrs/module/webservices/rest/doc/SwaggerSpecificationCreatorTest.java
* Fix invalid logic in SwaggerSpecificationCreator#hasSearchHandler(resourceName)
* Remove undeclared methods
* Remove unnecessary test case SwaggerSpecificationCreatorTest#swaggerSerializeTest()
Issue: [RESTWS-663](https://issues.openmrs.org/browse/RESTWS-663)
=> RESTWS-663 - Fix SwaggerSpecificationCreator#hasSearchHandler(resName)

omod-common/src/main/java/org/openmrs/module/webservices/docs/swagger/SwaggerSpecificationCreator.java, omod/src/main/java/org/openmrs/module/webservices/rest/web/controller/SwaggerSpecificationController.java, omod/src/test/java/org/openmrs/module/webservices/rest/doc/SwaggerSpecificationCreatorTest.java
* Make host and basePath not mandatory in SwaggerSpecificationCreator
* Set host and basePath to correct values in  SwaggerSpecificationController
Issue: https://issues.openmrs.org/browse/RESTWS-649
=> RESTWS-649 - Correct host property in OpenAPI Spec

omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/PatientIdentifierResource1_8.java, omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/PatientIdentifierController1_9Test.java
RESTWS-675: [Fix inability to retrieve soft deleted patient identifiers](https://issues.openmrs.org/browse/RESTWS-675)
This PR fixes Bug when retrieving non-active(soft deleted) patient identifiers
=> Bug when retrieving non-active(soft deleted) patient identifiers

omod-1.10/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_10/OrderableResource1_10.java, omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ModuleResource1_8.java, omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/TaskActionResource1_8.java, omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/ConceptSearchResource1_9.java, omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/CustomDatatypeHandlerResource1_9.java, omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/CustomDatatypeResource1_9.java, omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/BaseDelegatingResource.java, omod-common/src/test/java/org/mockingbird/test/rest/resource/AnimalClassResource_1_9.java, omod-common/src/test/java/org/mockingbird/test/rest/resource/AnimalResource_1_9.java, omod-common/src/test/java/org/mockingbird/test/rest/resource/BirdResource_1_9.java, omod-common/src/test/java/org/mockingbird/test/rest/resource/DuplicateNameAndOrderAnimalResource_1_9.java, omod-common/src/test/java/org/mockingbird/test/rest/resource/DuplicateNameAnimalResource_1_9.java, omod-common/src/test/java/org/mockingbird/test/rest/resource/InstantiateExceptionAnimalResource_1_9.java, omod-common/src/test/java/org/mockingbird/test/rest/resource/UnannotatedAnimalResource.java
Make `Model getCREATEModel(Representation rep)` optional, to avoid having to implement empty methods that returns just null, for resources that do not support CREATE operation and for test resources and the like.
Issue: https://issues.openmrs.org/browse/RESTWS-562
=> RESTWS-562 - Make getCREATEModel(Rep) method optional

omod-common/src/main/java/org/openmrs/module/webservices/docs/swagger/SwaggerSpecificationCreator.java, omod/src/main/java/org/openmrs/module/webservices/rest/Activator.java, omod/src/main/java/org/openmrs/module/webservices/rest/web/controller/SwaggerSpecificationController.java, omod/src/test/java/org/openmrs/module/webservices/rest/doc/SwaggerSpecificationCreatorTest.java
Generate and cache Swagger spec and clear it once every context refresh. If a cache exists SwaggerSpecificationCreator will serve the cached version instead of regenerating the spec.
Issue: https://issues.openmrs.org/browse/RESTWS-568
=> RESTWS-568 - Optimize Swagger spec creation

omod/src/main/java/org/openmrs/module/webservices/rest/web/controller/SwaggerSpecificationController.java
Change to get original host and the port values of the running server.
Talk thread: https://talk.openmrs.org/t/how-to-get-server-details-from-httpservletrequest/13554
Issue: [RESTWS-649](https://issues.openmrs.org/browse/RESTWS-649)
=> RESTWS-649 Update

omod-common/src/main/java/org/openmrs/module/webservices/docs/swagger/SwaggerSpecificationCreator.java
Use the permanent link to the wiki page:
https://wiki.openmrs.org/x/xoAaAQ
As the title-based URL could break if the page is moved or renamed in the future.
Sub-PR for: https://issues.openmrs.org/browse/RESTWS-560
=> RESTWS-560 Change extrenalDocs url to permanent link

omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/VisitResource1_9.java, omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/VisitController1_9Test.java
PDMO-60: [enable retrieving deleted Visits](https://issues.openmrs.org/browse/PDMO-60)
Fix bug in webservice to enable retrieving deleted Visits
=> [Bug] enable retrieving deleted Visits

omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ObsResource1_8.java, omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ObsController1_9Test.java
PDMO-65: [Enable retrieving soft deleted observations](https://issues.openmrs.org/browse/PDMO-65)
Fix bug in the webservice to enable retrieving soft deleted  observations.
=> PDMO-65: fix bug to enable retrieving soft deleted observations.

omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ModuleActionResource1_8.java, omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_8/ModuleActionController1_8Test.java, omod-common/src/main/java/org/openmrs/module/webservices/helper/ModuleAction.java
[RESTWS-688: Enable installation of modules through rest calls](https://issues.openmrs.org/browse/RESTWS-688)
Currently a module could not be installed through a REST call. When a REST call is made the module is to be downloaded on to the server, loaded and started.
=> RESTWS-688: Enable installation of modules through rest calls

omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ModuleActionResource1_8.java
[RESTWS-695: Fix issue with installation of modules](hhttps://issues.openmrs.org/browse/RESTWS-695)
When one installs or upgrades a module and restarts the server, the module does not appear under the list of installed modules.
=> RESTWS-695: Fix issue with installation of modules

omod-2.2/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/converter/openmrs2_2/CodedOrFreeTextConverter.java, omod-2.2/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/ConditionResource2_2.java, omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/RestTestConstants2_2.java, omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_2/ConditionController2_2Test.java, omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/ConditionResource2_2Test.java, omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/ProgramAttributeTypeResource2_2Test.java, omod-2.2/src/test/resources/conditionTestDataset.xml
Changed 1 file for this task:
* omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/RestTestConstants2_2.java
Added 5 files for this task:
* omod-2.2/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/ConditionResource2_2.java
* omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_2/ConditionController2_2Test.java
* omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/ConditionResource2_2Test.java
* omod-2.2/src/test/resources/conditionTestDataset.xml
* omod-2.2/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/converter/openmrs2_2/CodedOrFreeTextConverter.java
See https://issues.openmrs.org/browse/TRUNK-5350
No? -> …
=> TRUNK-5350: Introduce new REST APIs for the Condition domain object.

omod-1.11/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_11/EncounterRoleResource1_11.java, omod-1.11/src/test/java/org/openmrs/module/webservices/rest/web/RestTestConstants1_11.java, omod-1.11/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_11/EncounterRoleController1_11Test.java, omod-1.11/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_11/EncounterRoleResource1_11Test.java, omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/EncounterRoleResource1_9.java
Fix bug with `encounterRole` endpoint causing empty set `[ ]` to be returned when a query paramter in provider in API call
e.g `v1/encounterRole?q=unknown`
Issue: [RESTWS-707](https://issues.openmrs.org/browse/RESTWS-707)
=> RESTWS-707: Fix bug in encounterRole endpoint

omod-2.0/src/test/java/org/openmrs/module/unrelatedtest/UnrelatedGenericChild.java, omod-2.0/src/test/java/org/openmrs/module/unrelatedtest/rest/resource/UnrelatedGenericChildResource.java, omod-2.0/src/test/java/org/openmrs/module/webservices/rest/doc/SwaggerSpecificationCreatorTest.java, omod-common/src/main/java/org/openmrs/module/webservices/docs/swagger/SwaggerSpecificationCreator.java
Fix for ticket [RESTWS-721](https://issues.openmrs.org/browse/RESTWS-721). 
Add failing test checking for appropriate method calls and definitions in the compiled swagger.
Implement a fix deleting the offending code to allow tests to pass.
Builds on-top of #342 as changes required for tests to work.
=> RESTWS-721: Fix modules producing ref errors due to swagger exclusion

omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs1_9/EncounterSearchHandler1_9.java, omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs1_9/EncounterSearchHandler1_9Test.java
https://tickets.pih-emr.org/browse/UHM-3497
Fixed a bug where duplicate encounters were being returned from EncounterSearchHandler.
=> UHM-3497: Bug fix, do not return duplicate encounters for search by obs

omod-1.10/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_10/OrderFrequencyResource1_10.java, omod-1.10/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_10/OrderFrequencyController1_10Test.java
I added capability to create/save an order frequency using an existing Concept.
see https://issues.openmrs.org/browse/RESTWS-708
=> RESTWS-708 : Capability to add a new OrderFrequency via rest

omod-1.10/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_10/DrugOrderSubclassHandler1_10.java, omod-1.11/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_11/DrugResource1_11.java, omod-1.12/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_12/DrugOrderSubclassHandler1_12.java, omod-1.12/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_12/DrugResource1_12.java, omod-1.12/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_12/RestConstants1_12.java, omod-1.12/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_12/DrugResource1_12Test.java, omod-1.12/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_12/OrderController1_12Test.java, omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/RestTestConstants2_0.java
Ticket : https://issues.openmrs.org/browse/RESTWS-566
I  applied the DrugResource changes from platform 1.12 correctly to run when running platform 1.12
.
=> RESTWS-566: Applying the DrugResource changes from platform 1.12 correctly

omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/impl/DelegatingSubResource.java
RESTWS-735: Replace usages of the old newDelegate method
Replaced call to old newDelegate method with call to newDelegate(SimpleObject) so that post requests are handled correctly when instantiating new resource objects.
see https://issues.openmrs.org/browse/RESTWS-735
added all formatting changes to …
=> RESTWS-735: Replace usages of the old newDelegate method

omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/TaskActionResource1_8.java, omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_8/TaskActionController1_8Test.java, omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/SessionController1_9.java, omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/SessionController1_9Test.java
Adds sessionLocation to the user context object. The GET session endpoint now includes the location. The POST session endpoint now accepts a property `sessionLocation` which should be the UUID of a location. When POST is called, it also sets the location ID on the HttpSession, for compatibility with the appui endpoint.
This clashes with https://github.com/openmrs/openmrs-module-webservices.rest/pull/418 . Maintainers?
https://issues.openmrs.org/browse/RESTWS-758
=> RESTWS-758 Add location to session resource, with RESTful endpoints

omod-common/src/main/java/org/openmrs/module/webservices/rest/OpenmrsPathMatcher.java
Ticket ID:https://issues.openmrs.org/browse/TRUNK-5656
Description
Removed the Infinite recursive loop because method calls itself instead of delegate
=> TRUNK-5656: Fix infinite recursion in OpenmrsPathMatcher#matchStart

omod-1.11/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_11/DrugIngredientController1_11Test.java, omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_8/HL7MessageController1_8Test.java, omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_8/ServerLogController1_8Test.java, omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_8/TaskActionController1_8Test.java, omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_8/TaskDefinitionController1_8Test.java, omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ServerLogResource1_8Test.java, omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ConceptController1_8Test.java, omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ConceptController1_9Test.java, omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ObsController1_9Test.java, omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/PatientIdentifierController1_9Test.java, omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/PersonNameController1_9Test.java, omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/SessionController1_9Test.java, omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/VisitController1_9Test.java, omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/ConceptResource1_9Test.java, omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/PatientAllergyController2_0Test.java, omod-2.2/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_2/DiagnosisController2_2Test.java, omod-common/src/test/java/org/openmrs/module/webservices/rest/web/filter/ContentTypeFilterTest.java
17 files updated to correct order of arguments in Assert.assertequals statement.
https://issues.openmrs.org/browse/RESTWS-800
[x] My pull request only contains **ONE single commit**
[x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.
[ ] I have **added tests** to cover my changes. (If you refactored
[x] I ran `mvn clean package` right before creating this pull request and
[x ] All new and existing **tests passed**.
[x ] My pull request is **based on the latest changes** of the master branch.
=> RESTWS-800: Assertion arguments should be passed in the correct order

omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/MockModuleFactoryWrapper.java, omod-2.0/pom.xml, omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_0/AdministrationLinksResource2_0.java, omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/wrapper/AdministrationSectionLinks.java, omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/wrapper/AdministrationSectionLinks2_0.java, omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/AdministrationLinksController2_0Test.java, omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_0/AdministrationLinksResource2_0Test.java, omod-common/src/main/java/org/openmrs/module/webservices/helper/ModuleFactoryWrapper.java, omod-common/src/main/java/org/openmrs/module/webservices/rest/web/response/ObjectNotFoundException.java
Added REST resource with links to administration pages of installed modules.
It can return a list of all administration links for installed modules at `/openmrs/ws/rest/v1/administration-links/`.
It can also return list of administration links for given module id at `/openmrs/ws/rest/v1/administration-links/{moduleId}`.
Example response body can be found here: [https://pastebin.com/q2deZqaL](https://pastebin.com/q2deZqaL)
PR with documentation: [https://github.com/openmrs/openmrs-contrib-rest-api-docs/pull/140](https://github.com/openmrs/openmrs-contrib-rest-api-docs/pull/140)
To not rely on LegacyUI, I've copied AdministrationSectionExt from [https://github.com/openmrs/openmrs-module-legacyui/blob/master/omod/src/main/java/org/openmrs/module/web/extension/AdministrationSectionExt.java](ht …
=> RESTWS-821: Add REST resource with links to administration pages of installed modules

omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_0/DatabaseChangeResource2_0.java, omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/DatabaseChangeController2_0Test.java, omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_0/DatabaseChangeResource2_0Test.java
Added DatabaseChangeResource2_0 that allows listing all OpenMRSChangeSets and listing one by its id.
see https://issues.openmrs.org/browse/RESTWS-834
PR with documentation: https://github.com/openmrs/openmrs-contrib-rest-api-docs/pull/154
No? -> execute …
=> RESTWS-834: Add REST resource for Database Changes

omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_0/ConceptStateConversionResource2_0.java, omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/ConceptStateConversionController2_0Test.java, omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_0/ConceptStateConversionResource2_0Test.java
Added REST resource for Triggered State Conversions management
see https://issues.openmrs.org/browse/RESTWS-836
PR with documentation: https://github.com/openmrs/openmrs-contrib-rest-api-docs/pull/158
No? -> figure out why and …
=> RESTWS-836: Add REST resource for Triggered State Conversions management

omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/FieldTypeResource1_8.java, omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_8/FieldTypeController1_8Test.java
I've added the ability to create FieldType with `isSet` field via REST API.
see https://issues.openmrs.org/browse/RESTWS-832
PR with updated documentation: https://github.com/openmrs/openmrs-contrib-rest-api-docs/pull/162
No? -> …
=> RESTWS-832: Update REST resource for Field Types management

omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/LoggedInUsersController2_0.java, omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/LoggedInUsersController2_0Test.java
Added LoggedInUsersController2_0 that allows querying logged-in users.
see https://issues.openmrs.org/browse/RESTWS-835
PR with documentation: https://github.com/openmrs/openmrs-contrib-rest-api-docs/pull/164
No? -> figure out …
=> RESTWS-835: Add REST resource for Logged In Users

omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/ConceptAttributeTypeController2_0Test.java
Created a new class `ConceptAttributeTypeController2_0Test `to cater for the `getURL()` of the ConceptAttributeType and create method
see https://issues.openmrs.org/browse/RESTWS-856
=> RESTWS-856: Concept Attribute Types Create Test Endpoint

omod-2.0/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_0/ConceptAttributeTypeController2_0Test.java
I added an end point test for returning a list of concept attribute types
[RESTWS-874](https://issues.openmrs.org/browse/RESTWS-874)
- [ x] All new and existing **tests …
=> RESTWS-874: Fix End Point-Concept Attribute Types list test

omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/SessionController1_9.java
In case a DELETE call is not accompanied with a JSESSIONID (e.g. in case of COOKIE expiry), the current code was invalidating a newly created session, resulting in subsequent calls failing with the JSESSIONID sent back thats already invalidated. (the user can not proceed without clearing the app cache or waiting for the cookie to expire)
=> RESTWS-905 | Session should be invalidated only if its a valid session

omod-1.10/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_10/OrderResource1_10.java, omod-1.10/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_10/OrderController1_10Test.java
see https://issues.openmrs.org/browse/RESTWS-716
=> RESTWS-716: Orders resource returns no results when only status is specified

omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/FormResource1_8.java
[see https://issues.openmrs.org/browse/RESTWS-923](https://issues.openmrs.org/browse/RESTWS-923)
- [ x] I ran `mvn clean package` right before creating this pull request and
- [x ] All new and existing **tests passed**.
No? -> figure out why and add the fix to your …
=> RESTWS-923: Filter out retired forms in /forms endpoint

omod-common/src/main/java/org/openmrs/module/webservices/rest/web/ConversionUtil.java, omod-common/src/test/java/org/openmrs/module/webservices/rest/web/ConversionUtilTest.java
The PR done with RESTWS-901 introduced a regression in the patient registration steps.
If concepts are used for some attributes ( civil status) there are now saved with their uuid in the database ( table `person_attribute`) and no more with the concept_id.
… (#581)"
This reverts commit cbcf07f27ada8d73f2954fce7cf126987b84b5cf.
see https://issues.openmrs.org/browse/RESTWS-933
No? -> figure out why …
=> RESTWS-933: Revert RESTWS-901 due to issue saving coded pt attrs

omod-common/src/main/java/org/openmrs/module/webservices/rest/web/RestUtil.java, pom.xml
After https://github.com/openmrs/openmrs-core/pull/4601, users must possess the 'Get Global Properties' privilege to access global properties. This grants it as a proxy privilege so users can access essential pages, such as the login page.
see https://openmrs.atlassian.net/browse/TRUNK-6203
No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code …
=> TRUNK-6203: Global properties access should be privileged

omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/PersonAttributeResource1_8.java, omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/PersonAttributeResource1_8Test.java, omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_9/CreateUpdatePatientResource1_9Test.java
Previously, `PersonAttributeResource1_8#getDisplayString()` had two different formats:
1. For attributes without an attribute type, an empty string
2. For concepts, the concept display string
3. For anything else, `AttributeType = <AttributeValue>`; e.g., `Current Location = 4`
This PR ensures that `getDisplayString()` continues to work like 1 and 2 above, but replaces 3 with something more similar to 2, that is, the display string for the value. This means that in the `Current Location` example above, `getDisplayString()` would return a string like "Ward 3".
The AttributeType name can be fetched via a custom display, and the raw value can be read via the `value` property. Nevertheless, this is technically a breaking change.
see https://issues.openmrs.org/browse/RESTWS-940
No? Unsure? -> …
=> RESTWS-940: PersonAttributeResource should not try to hydrate the attribute itself

omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_8/PatientIdentifierTypeController1_8Test.java, omod-common/src/main/java/org/openmrs/module/webservices/rest/web/ConversionUtil.java, omod-common/src/test/java/org/openmrs/module/webservices/rest/web/ConversionUtilTest.java
This issue is that, `ConversionUtil#convertToRepresentation(object, representation, converter)`, does not use the `representation` param, when the `object` param is of type `Map`. So it'll always return an object with all the elements in the map, even if the caller wants to convert it to a custom representation.
https://github.com/openmrs/openmrs-module-webservices.rest/blob/6d01f5fdef274903c242645456c7d5a7fab0a9e7/omod-common/src/main/java/org/openmrs/module/webservices/rest/web/ConversionUtil.java#L379-L397
As shown below every value in the map is converted to it's `REF` representation.
https://github.com/openmrs/openmrs-module-webservices.rest/blob/6d01f5fdef274903c242645456c7d5a7fab0a9e7/omod-common/src/main/java/org/openmrs/module/webservices/rest/web/ConversionUtil.java#L393-L395 …
=> RESTWS-904 Support custom representation for Map objects

omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs2_0/EncounterSearchHandler2_0.java
=> RestWS-950-Encounter Search Handler should support a visits parameter

omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/ObsResource1_8.java, omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs1_8/ConceptSearchHandler1_8.java, omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ConceptReferenceController1_9.java, omod-common/src/main/java/org/openmrs/module/webservices/rest/web/RestUtil.java
=> RESTWS-953: Support setting values of type "Location"

omod-1.9/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/SessionController1_9.java, omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/SessionController1_9Test.java
Made sure we have locale details in the json return when a user is not logged. The json below is extracted from the network after dropping an omod file with the changes into a local server to test the changes in this PR.
```
{
"authenticated": false,
"locale": "en",
"allowedLocales": [
"en",
"en-GB",
"es",
"fr",
"he",
"km",
"ar"
]
}
```
see https://issues.openmrs.org/browse/RESTWS-954
No? -> …
=> RESTWS-954: Ensures session endpoint returns locale even when user is not logged in

omod-common/src/main/java/org/openmrs/module/webservices/docs/swagger/SwaggerSpecificationCreator.java
=> Improve Swagger typings for getAll

omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/PersonAttributeResource1_8.java, omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/PersonAttributeResource1_8Test.java
see https://issues.openmrs.org/browse/RESTWS-955
=> RESTWS-955: Add support for person attribute of type Location

omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/PersonAttributeResource1_8.java, omod-1.8/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs1_8/PersonAttributeResource1_8Test.java, omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/PersonAttributeController1_9Test.java
see https://issues.openmrs.org/browse/RESTWS-955
=> RESTWS-955: Fix adding support for locations as person attributes

omod-2.0/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs2_0/EncounterSearchHandler2_0.java
Return empty result when the specified encounter type is not found
see https://openmrs.atlassian.net/browse/RESTWS-962
=> RESTWS-962: Return empty result when the specified encounter type is not found

omod-common/src/main/java/org/openmrs/module/webservices/rest/web/RestConstants.java
This PR fixes an issue where adding the `totalCount=true` parameter to observation search requests causes the request to bypass the ObservationSearchHandler1_8 and fall back to ObsResource1_8.doSearch(), resulting in inconsistent filtering behavior.
The root cause was that `totalCount` was not included in the SPECIAL_REQUEST_PARAMETERS set in RestConstants.java. When present in a request, it was treated as a regular parameter affecting handler selection. Since ObservationSearchHandler1_8 doesn't declare `totalCount` as a parameter, requests with this parameter were not being routed to it.
By adding `totalCount` to SPECIAL_REQUEST_PARAMETERS, we ensure it doesn't affect handler selection while still being available for pagination functionality. This allows observation searches to be …
=> RESTWS-943 : ObservationSearchHandler should be chosen to handle obs search request when `totalCount` is passed in

omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/ConversionUtil1_9Test.java, omod-common/src/main/java/org/openmrs/module/webservices/rest/web/ConversionUtil.java
see https://issues.openmrs.org/browse/RESTWS-979
Note, in addition to the unit test included here which demonstrates the issue, I have verified that this also fixes the test that I was attempting to write in EMR API that first caused me to investigate this issue.
=> RESTWS-979 - Custom representations are not parsed correctly

omod-2.4/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_2/PasswordResetController2_2.java, omod-2.4/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs2_2/PasswordResetController2_2Test.java
see https://issues.openmrs.org/browse/RESTWS-885
=> RESTWS-885: Reset password REST endpoint requires privileges
